data:
  dataset: "tiny"
  extension: "wav"
  input: LB
  
preprocess:
  sampling_rate: &samplingrate 16000
  signal_length: &signallength 64000
  block_size: &blocksize 256 # must be a power of 2 if using realtime
  oneshot: false # crop every audio file to exactly signal length

model:
  hidden_size: 512
  n_harmonics: 100
  n_bands: 65
  sampling_rate: *samplingrate
  block_size: *blocksize
  device: cpu

train:
  model: "resnet"
  scales: [2048, 1024, 512, 256, 128, 64]
  overlap: .75
  batch: 32
  HF: False