data:
  dataset: gtzan
  extension: wav
  input: LB
  mean_loudness: -11.504433484673505
  std_loudness: 0.9554695709887904
model:
  block_size: 256
  device: cpu
  hidden_size: 512
  max_sources: 5
  n_bands: 65
  n_harmonics: 100
  sampling_rate: 16000
preprocess:
  block_size: 256
  downsampling_factor: 4
  oneshot: false
  sampling_rate: 16000
  signal_length: 64000
train:
  HF: true
  batch: 2
  model: ddsp_poly_decoder
  overlap: 0.75
  scales:
  - 2048
  - 1024
  - 512
  - 256
  - 128
  - 64
  start_lr: 0.001
  stop_lr: 0.0001
